config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  post "/xmlrpc.php", to: "application#error_render_method"

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}

  root to: 'home#index'
  # Switch to this for maintenance mode
  # root to: 'home#maintenance'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations:  'users/registrations'
  }

  # devise_scope :user do
  #   authenticated :user do
  #     root :to => 'pages#other', as: :authenticated_root
  #   end
  #   unauthenticated :user do
  #     root :to => 'sessions#new', as: :unauthenticated_root
  #   end
  # end

  devise_for :companies, controllers: {
    sessions:       'companies/sessions',
    registrations:  'companies/registrations'
  }


  # Admins only *** NOT Superadmins! ***
  authenticated :user, lambda { |u| u.admin? } do
  # devise_scope :companies do
    root to: "companies#main"

    post '/users/new', to: 'users#existence_check'

    get  'companies/branch_view',         to: "companies#branch_view"
    # post 'companies/branch_view',         to: "companies#branch_view"

    get  'companies/add_employee',        to: "companies#add_employee"
    # post 'companies/add_employee',        to: "companies#add_employee"

    post 'companies/toggle_admin',        to: "companies#toggle_admin"

    post 'companies/toggle_employee_status',        to: "application#toggle_employee_status"

    get  'companies/manage_employees',    to: "companies#manage_employees"
    # post 'companies/manage_employees',    to: "companies#manage_employees"

    get  'companies/homepage',            to: "companies#main"
    # post 'companies/homepage',            to: "companies#main"

    post 'companies/remove_employee', to: "application#remove_employee"

    # post '/download_validator',           to: "orders#download_validator"

    get '/assign_identifier',             to: "companies#assign_identifier"

    post '/assign_parent_company',        to: "companies#assign_parent_company"

    post '/remove_parent_company',        to: "companies#remove_parent_company"

    match '/assign_course', to: "companies#assign_course", via: [:get, :post]

    post 'companies/assign_multiple_courses',    to: "companies#assign_multiple_courses"

    get  'companies/orders',  to: "companies#company_orders"
    get  'companies/reports', to: "companies#company_reports"
    post '/get_talent_user_id', to: "talent#get_talent_user_id"

    # TODO Some of these should be moved to Superadmin!
    # get  'unpaid_orders',     to: "orders#unpaid_orders"
    # post 'invoiced',          to: "orders#invoiced"
    # post 'labeled',           to: "orders#labeled"
    # post 'order_paid',        to: "orders#order_paid"
    get  'mark_all_as_read',  to: "application#mark_all_as_read"
    post 'import_employees',  to: "companies#import_employees"

    resources :users # , only: [:show]
  # end

  # devise_scope :admin do
    get '/add_employee',            to: "users#add_employee"
    get '/manage_employees',        to: "users#manage_employees"
    post '/remove_employee',        to: "application#remove_employee"
    post '/toggle_employee_status', to: "application#toggle_employee_status"
    post '/make_assignable',        to: 'application#make_assignable'
  end

  # Superadmins only
  authenticated :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'

    resources :alt_names
    resources :backups
    resources :bulk_price_levels
    resources :button_groups
    resources :buttons
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychain_groups
    resources :keychains
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tag_groups
    resources :machine_tags
    resources :online_courses
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :product_groups
    resources :related_items
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users
    get  '/analytics',        to: 'reports#analytics'
    post '/assign_non_catalog_course', to: 'superadmin#assign_non_catalog_course'
    post 'invoiced',          to: "orders#invoiced"
    post 'labeled',           to: "orders#labeled"
    get  '/labels_required',  to: "users#labels_required"
    post 'order_paid',        to: "orders#order_paid"
    post 'related_items/new', to: "related_items#new"
    post '/reset_download_window',     to: 'superadmin#reset_download_window'
    get  'unpaid_orders',     to: "orders#unpaid_orders"
  end

  # These are required for things to show up in Administrate.
  namespace :admin do
    resources :alt_names
    resources :announcements
    resources :backups
    resources :bulk_price_levels
    resources :buttons
    resources :button_groups
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychains
    resources :keychain_groups
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tags
    resources :machine_tag_groups
    resources :non_catalog_course_accesses
    resources :notifications
    resources :orders do
      member do
        put :refund
      end
    end
    resources :online_courses
    resources :order_items #, only: [:create, :update]
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :products
    resources :product_groups
    resources :services
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users

    root to: "users#index"
  end

  # PUBLIC ROUTES
  get  'add_tag',               to: "product_groups#add_tag"
  get '/all_group_trainings',   to: 'home#all_group_trainings'
  get '/all_online_courses',    to: 'home#all_online_courses'
  post '/sales',                to: 'reports#sales'
  get '/all_train_the_trainer_courses',    to: 'home#all_train_the_trainer_courses'
  get  'remove_tag',            to: "product_groups#remove_tag"
  post  'add_tag_global',       to: "product_groups#add_tag_global"
  post  'remove_tag_global',    to: "product_groups#remove_tag_global"

  post '/add_to_course',        to: 'talent#online_course_validator'
  post '/add_backup',           to: 'order_items#add_backup'
  post '/add_shipping_address', to: 'checkouts#add_shipping_address'
  get '/about',                 to: 'home#about'
  get '/canadian_group_trainings',to: 'home#canadian_group_trainings'
  get '/canadian_online_courses',to: 'home#canadian_online_courses'
  get '/canadian_train_the_trainer_courses',to: 'home#canadian_train_the_trainer_courses'
  get '/canadian_training_kits',to: 'home#canadian_training_kits'
  get '/change_shipping',       to: 'orders#change_shipping'
  get '/contact_us',            to: 'home#contact'
  # This allows users to get their downloads from Orders!
  post '/download_validator',   to: "orders#download_validator"
  get '/diy_training_kits',     to: 'home#diy_training_kits'
  post '/edit_tag',             to: "tags#edit"
  get '/faq',                   to: 'home#faq'
  get '/course',                to: 'product_groups#course'
  post '/get_certificate',      to: 'talent#get_cert'
  get '/osha_group_trainings',  to: 'home#osha_group_trainings'
  get '/osha_online_courses',   to: 'home#osha_online_courses'
  get '/osha_train_the_trainer_courses',    to: 'home#osha_train_the_trainer_courses'
  get '/osha_training_kits',    to: 'home#osha_training_kits'
  get '/spanish_group_trainings',to: 'home#spanish_group_trainings'
  get '/spanish_online_courses',to: 'home#spanish_online_courses'
  get '/spanish_train_the_trainer_courses', to: 'home#spanish_train_the_trainer_courses'
  get '/spanish_training_kits', to: 'home#spanish_training_kits'
  get '/tagalog_group_trainings',to: 'home#tagalog_group_trainings'
  get '/tagalog_online_courses',to: 'home#tagalog_online_courses'
  get '/tagalog_train_the_trainer_courses', to: 'home#tagalog_train_the_trainer_courses'
  get '/tagalog_training_kits', to: 'home#tagalog_training_kits'
  post '/talent_login',         to: 'talent#log_into_talent'
  get '/training_topics',       to: 'home#topics'
  post '/update_tag',           to: "tags#update"
  post '/reset_password',       to: "application#reset_password"

  match '/onsite_request',      to: "home#onsite_training", via: [:get, :post]

  get '/remove_coupon_code',  to: "orders#remove_coupon_code"
  get '/search',              to: 'home#search'
  post '/send_contact_email', to: 'home#send_contact_email'
  get '/privacy',             to: 'home#privacy'
  get '/terms',               to: 'home#terms'
  get '/training_types',      to: 'home#training_types'
  post '/update_preferred_currency',      to: 'home#update_preferred_currency'
  get '/verify_code',         to: "orders#verify_code"
  get '/documentation',       to: 'documents#index'
  get 'employee_list',        to: 'reports#employee_list'
  get 'reports',              to: 'reports#index'

  resources :announcements, only: [:index]
  resources :button_groups, only: [:show, :index]
  resources :card_groups, only: [:show]
  resource :cart do
    resource :checkout
  end
  resources :certificates, only: [:show]
  resources :companies
  resources :credit_packs, only: [:index]
  resources :hats, only: [:show, :index]
  resources :keychain_groups, only: [:show]
  # TODO Should these be here? They are purchased through their ProductGroup

app/models/payment_term.rb
class PaymentTerm < ApplicationRecord
  belongs_to :company

  # enum term:  [:thirty, :forty_five, :sixty]

  validates_presence_of :term
  validates_numericality_of :term

  validates :company, presence: true, uniqueness: true

end

app/controllers/admin/payment_terms_controller.rb
module Admin
  class PaymentTermsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = PaymentTerm.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   PaymentTerm.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/payment_terms_controller.rb
class PaymentTermsController < ApplicationController
  before_action :set_payment_term, only: [:show, :edit, :update, :destroy]

  def index
    @payment_terms = PaymentTerm.all
    authorize @payment_terms
  end

  def show
  end

  def new
    @payment_term = PaymentTerm.new
    authorize @payment_term
    @companies = Company.all.order(name: :asc).pluck(:id, :name, :city, :state)
  end

  def edit
  end

  def create
    @payment_term = PaymentTerm.new(payment_term_params)
    authorize @payment_term

    respond_to do |format|
      if @payment_term.save
        format.html { redirect_to @payment_term, notice: 'Payment term was successfully created.' }
        format.json { render :show, status: :created, location: @payment_term }
      else
        format.html { render :new }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment_term.update(payment_term_params)
        format.html { redirect_to @payment_term, notice: 'Payment term was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_term }
      else
        format.html { render :edit }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment_term.destroy
    respond_to do |format|
      format.html { redirect_to payment_terms_url, notice: 'Payment term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_payment_term
      @payment_term = PaymentTerm.find(params[:id])
      authorize @payment_term
    end

    def payment_term_params
      params.require(:payment_term).permit(:company_id, :term)
    end
end

app/helpers/payment_terms_helper.rb
module PaymentTermsHelper
end

app/views/payment_terms/_form.html.erb
<%= form_with(model: payment_term, local: true) do |form| %>
  <% if payment_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_term.errors.count, "error") %> prohibited this payment_term from being saved:</h2>

      <ul>
      <% payment_term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-4 offset-sm-4 col-lg-2 offset-lg-5">
    <%= form.number_field :company_id, class: 'form-control', placeholder: "Company ID" %>
    <p>
      <%# Button trigger modal %>
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#companyIdModal">
        Find Company ID
      </button>
    </p>
  </div>

  <div class="form-group col-sm-4 offset-sm-4 col-lg-2 offset-lg-5">
    <%= form.label :term %>
    <%= form.select :term, options_for_select([["30 Days", 30], ["45 Days", 45], ["60 Days", 60]]) %>
  </div>

  <div class="form-group">
    <% if payment_term.persisted? && current_user.superadmin? %>
      <div class="float-right">
        <%= link_to 'Destroy', payment_term, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary btn-spinner' %>

    <% if payment_term.persisted? %>
      <%= link_to "Cancel", payment_term, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", payment_terms_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

<% unless Rails.env.test? %>
  <%# Modal %>
  <div class="modal fade" id="companyIdModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Find A Company ID</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% @companies.each do |c| %>
            <h5>ID <%= c[0] %>: <%= c[1] %> (<%= c[2] + ', ' + c[3] %>)</h5>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/payment_terms/edit.html.erb
<h1 class="h1-margins">Edit Payment Term</h1>

<%= render 'form', payment_term: @payment_term %>

app/views/payment_terms/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Payment Terms</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_payment_term_path, class: 'btn btn-primary' do %>
    Add New Payment Term
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

        <th>Company</th>
        <th>Term</th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @payment_terms.each do |payment_term| %>
        <%= content_tag :tr, id: dom_id(payment_term), class: dom_class(payment_term) do %>

          <td><%= payment_term.company.name %></td>
          <td><%= payment_term.term %> days</td>
          <td><%= link_to 'Show', payment_term %></td>

        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/payment_terms/new.html.erb
<h1 class="h1-margins">New Payment Term</h1>

<%= render 'form', payment_term: @payment_term %>

app/views/payment_terms/show.html.erb
<div class="page-header">
  <%= link_to payment_terms_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Payment_terms
  <% end %>
  <%= link_to edit_payment_term_path(@payment_term), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show payment_term</h1>
</div>

<dl class="dl-horizontal">
  <dt>Company:</dt>
  <dd><%= @payment_term.company %></dd>

  <dt>Term:</dt>
  <dd><%= @payment_term.term %></dd>

</dl>