config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  post "/xmlrpc.php", to: "application#error_render_method"

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}

  root to: 'home#index'
  # Switch to this for maintenance mode
  # root to: 'home#maintenance'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations:  'users/registrations'
  }

  # devise_scope :user do
  #   authenticated :user do
  #     root :to => 'pages#other', as: :authenticated_root
  #   end
  #   unauthenticated :user do
  #     root :to => 'sessions#new', as: :unauthenticated_root
  #   end
  # end

  devise_for :companies, controllers: {
    sessions:       'companies/sessions',
    registrations:  'companies/registrations'
  }


  # Admins only *** NOT Superadmins! ***
  authenticated :user, lambda { |u| u.admin? } do
  # devise_scope :companies do
    root to: "companies#main"

    post '/users/new', to: 'users#existence_check'

    get  'companies/branch_view',         to: "companies#branch_view"
    # post 'companies/branch_view',         to: "companies#branch_view"

    get  'companies/add_employee',        to: "companies#add_employee"
    # post 'companies/add_employee',        to: "companies#add_employee"

    post 'companies/toggle_admin',        to: "companies#toggle_admin"

    post 'companies/toggle_employee_status',        to: "application#toggle_employee_status"

    get  'companies/manage_employees',    to: "companies#manage_employees"
    # post 'companies/manage_employees',    to: "companies#manage_employees"

    get  'companies/homepage',            to: "companies#main"
    # post 'companies/homepage',            to: "companies#main"

    post 'companies/remove_employee', to: "application#remove_employee"

    # post '/download_validator',           to: "orders#download_validator"

    get '/assign_identifier',             to: "companies#assign_identifier"

    post '/assign_parent_company',        to: "companies#assign_parent_company"

    post '/remove_parent_company',        to: "companies#remove_parent_company"

    match '/assign_course', to: "companies#assign_course", via: [:get, :post]

    post 'companies/assign_multiple_courses',    to: "companies#assign_multiple_courses"

    get  'companies/orders',  to: "companies#company_orders"
    get  'companies/reports', to: "companies#company_reports"
    post '/get_talent_user_id', to: "talent#get_talent_user_id"

    # TODO Some of these should be moved to Superadmin!
    # get  'unpaid_orders',     to: "orders#unpaid_orders"
    # post 'invoiced',          to: "orders#invoiced"
    # post 'labeled',           to: "orders#labeled"
    # post 'order_paid',        to: "orders#order_paid"
    get  'mark_all_as_read',  to: "application#mark_all_as_read"
    post 'import_employees',  to: "companies#import_employees"

    resources :users # , only: [:show]
  # end

  # devise_scope :admin do
    get '/add_employee',            to: "users#add_employee"
    get '/manage_employees',        to: "users#manage_employees"
    post '/remove_employee',        to: "application#remove_employee"
    post '/toggle_employee_status', to: "application#toggle_employee_status"
    post '/make_assignable',        to: 'application#make_assignable'
  end

  # Superadmins only
  authenticated :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'

    resources :alt_names
    resources :backups
    resources :bulk_price_levels
    resources :button_groups
    resources :buttons
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychain_groups
    resources :keychains
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tag_groups
    resources :machine_tags
    resources :online_courses
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :product_groups
    resources :related_items
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users
    get  '/analytics',        to: 'reports#analytics'
    post '/assign_non_catalog_course', to: 'superadmin#assign_non_catalog_course'
    post 'invoiced',          to: "orders#invoiced"
    post 'labeled',           to: "orders#labeled"
    get  '/labels_required',  to: "users#labels_required"
    post 'order_paid',        to: "orders#order_paid"
    post 'related_items/new', to: "related_items#new"
    post '/reset_download_window',     to: 'superadmin#reset_download_window'
    get  'unpaid_orders',     to: "orders#unpaid_orders"
  end

  # These are required for things to show up in Administrate.
  namespace :admin do
    resources :alt_names
    resources :announcements
    resources :backups
    resources :bulk_price_levels
    resources :buttons
    resources :button_groups
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychains
    resources :keychain_groups
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tags
    resources :machine_tag_groups
    resources :non_catalog_course_accesses
    resources :notifications
    resources :orders do
      member do
        put :refund
      end
    end
    resources :online_courses
    resources :order_items #, only: [:create, :update]
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :products
    resources :product_groups
    resources :services
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users

    root to: "users#index"
  end

  # PUBLIC ROUTES
  get  'add_tag',               to: "product_groups#add_tag"
  get '/all_group_trainings',   to: 'home#all_group_trainings'
  get '/all_online_courses',    to: 'home#all_online_courses'
  post '/sales',                to: 'reports#sales'
  get '/all_train_the_trainer_courses',    to: 'home#all_train_the_trainer_courses'
  get  'remove_tag',            to: "product_groups#remove_tag"
  post  'add_tag_global',       to: "product_groups#add_tag_global"
  post  'remove_tag_global',    to: "product_groups#remove_tag_global"

  post '/add_to_course',        to: 'talent#online_course_validator'
  post '/add_backup',           to: 'order_items#add_backup'
  post '/add_shipping_address', to: 'checkouts#add_shipping_address'
  get '/about',                 to: 'home#about'
  get '/canadian_group_trainings',to: 'home#canadian_group_trainings'
  get '/canadian_online_courses',to: 'home#canadian_online_courses'
  get '/canadian_train_the_trainer_courses',to: 'home#canadian_train_the_trainer_courses'
  get '/canadian_training_kits',to: 'home#canadian_training_kits'
  get '/change_shipping',       to: 'orders#change_shipping'
  get '/contact_us',            to: 'home#contact'
  # This allows users to get their downloads from Orders!
  post '/download_validator',   to: "orders#download_validator"
  get '/diy_training_kits',     to: 'home#diy_training_kits'
  post '/edit_tag',             to: "tags#edit"
  get '/faq',                   to: 'home#faq'
  get '/course',                to: 'product_groups#course'
  post '/get_certificate',      to: 'talent#get_cert'
  get '/osha_group_trainings',  to: 'home#osha_group_trainings'
  get '/osha_online_courses',   to: 'home#osha_online_courses'
  get '/osha_train_the_trainer_courses',    to: 'home#osha_train_the_trainer_courses'
  get '/osha_training_kits',    to: 'home#osha_training_kits'
  get '/spanish_group_trainings',to: 'home#spanish_group_trainings'
  get '/spanish_online_courses',to: 'home#spanish_online_courses'
  get '/spanish_train_the_trainer_courses', to: 'home#spanish_train_the_trainer_courses'
  get '/spanish_training_kits', to: 'home#spanish_training_kits'
  get '/tagalog_group_trainings',to: 'home#tagalog_group_trainings'
  get '/tagalog_online_courses',to: 'home#tagalog_online_courses'
  get '/tagalog_train_the_trainer_courses', to: 'home#tagalog_train_the_trainer_courses'
  get '/tagalog_training_kits', to: 'home#tagalog_training_kits'
  post '/talent_login',         to: 'talent#log_into_talent'
  get '/training_topics',       to: 'home#topics'
  post '/update_tag',           to: "tags#update"
  post '/reset_password',       to: "application#reset_password"

  match '/onsite_request',      to: "home#onsite_training", via: [:get, :post]

  get '/remove_coupon_code',  to: "orders#remove_coupon_code"
  get '/search',              to: 'home#search'
  post '/send_contact_email', to: 'home#send_contact_email'
  get '/privacy',             to: 'home#privacy'
  get '/terms',               to: 'home#terms'
  get '/training_types',      to: 'home#training_types'
  post '/update_preferred_currency',      to: 'home#update_preferred_currency'
  get '/verify_code',         to: "orders#verify_code"
  get '/documentation',       to: 'documents#index'
  get 'employee_list',        to: 'reports#employee_list'
  get 'reports',              to: 'reports#index'

  resources :announcements, only: [:index]
  resources :button_groups, only: [:show, :index]
  resources :card_groups, only: [:show]
  resource :cart do
    resource :checkout
  end
  resources :certificates, only: [:show]
  resources :companies
  resources :credit_packs, only: [:index]
  resources :hats, only: [:show, :index]
  resources :keychain_groups, only: [:show]
  # TODO Should these be here? They are purchased through their ProductGroup

app/models/home.rb
class Home < ActiveRecord::Base
   acts_as_taggable_on :tags
end

app/views/home/about.html.erb
<div id="about-page" class="content-container">
  <div>
    <h1>About Us</h1>

    <h3 class="text-left">History:</h3>
    <p>
      Hard Hat Training has been providing heavy equipment operator training services across the U.S. and Canada for nearly two decades. Our story started over 15 years ago in the Seattle area where we specialized in the inspection, testing, and certification of cranes. To this day, those same inspectors travel all over the country and even outside the country inspecting cranes and training heavy equipment operators. Our Hard Hat Training Series training tools have also become commonplace across the globe. Most recently, Africa, Abu Dhabi, and the United Arab Emirates have become markets filled with companies using our online training classes and customizable training kits to train their heavy equipment operators.
    </p>
  </div>

  <div>
    <h3 class="text-left">Mission Statement:</h3>
    <p>
      Bottom line, our goal is to make safety training easy and affordable, and to invite companies everywhere to stop doing things the hard way and, instead, start doing them the Hard Hat Training way!
    </p>
  </div>

  <div>
    <h3 class="text-left">Purpose:</h3>
    <p>
      Our products are designed to help you save money while professionally training your own employees and customers. We help you stay compliant by doing the research and design work so you don’t have to.
    </p>

    <p>
      The days of 15-minute operator certification via video or online course are over. It is simply not sufficient, and if there is ever an accident, you will need to be able to prove comprehensive training. So in a day and age when safety training is getting shorter, we keep adding to ours, making it more comprehensive in order to protect your company and your employees.
    </p>

    <p>
      Since those early days inspecting cranes and offering on-site crane training classes, we’ve become a hub for low cost, high quality OSHA-compliant training tools for all types of heavy equipment operations including but not limited to: aerial boom lifts, scissor lifts, bucket trucks, forklifts, telescopic handlers (zoom booms), skid steers, front-end loaders, excavators, mobile cranes, overhead cranes, rigger signalman, trench safety, scaffolding and more. We are also constantly updating, translating and adding to our catalog. Coming Soon: Fall Protection, Confined Space, Lockout Tagout, Hazard Communications, and more.
    </p>

    <p>
      Our OSHA compliant training kits and OSHA online training courses are trusted by companies around the world in virtually every industry.
    </p>

    <p>
      And for our customers in Canada, we’ve worked non-stop with leading safety companies across your country in order to release Canada-compliant versions of these same training kits (each training kit comes with additional federal and provincial training and safety helps) and online training courses for Canadian operators.  In fact, our online classes are our biggest sellers in Canada–used in virtually every province by companies such as Leavitt Machinery, SafeTech Training, City of Toronto, and others.
    </p>
  </div>

  <%= render 'shared/meet_our_team' %>

  <div>
    <h3 class="text-left">Contact Us:</h3>
    <p>
      If you are interested in more information or wish to express interest in our services, products, or distribution opportunities please <%= link_to 'contact us', contact_us_path  %> today.
    </p>
  </div>

  <div>
    <h3 class="text-left">Acknowledgments</h3>

    <p>
      We would like to thank the following for the use of their photos in our products:
    </p>

    <ul>
      <li><%= link_to 'AAAnimal Control', "http://www.aaanimalcontrol.com/", target: "_blank" %> <%= icon("fas", "external-link-alt") %></li>
      <li><%= link_to 'Grizzly & Wolf Discovery Center', "https://www.grizzlydiscoveryctr.org/", target: "_blank" %> <%= icon("fas", "external-link-alt") %></li>
      <li><%= link_to 'Cap Vectors by Vecteezy', "https://www.vecteezy.com/free-vector/cap/", target: "_blank" %> <%= icon("fas", "external-link-alt") %></li>
    </ul>

    <p>
      Some Font Awesome icons used, without modification, under the <a href="https://fontawesome.com"> Creative Commons Attribution 4.0 International license</a>.
    </p>
  </div>
</div>

app/views/home/all_train_the_trainer_courses.html.erb
<div id="all-online-courses-page">
  <h1>Train The Trainer Courses<br/>All Standards And Languages</h1>

  <h3 class="h3-margins">
    Get Certified and Train Your Own Employees
  </h3>

  <h5>Lifetime Certification<br/>
  DIY Kit Included FREE ($400 value!)</h5>

  <%= render 'shared/train_the_trainer_header' %>

  <%= render 'shared/diy_kits_page' %>
</div>

app/views/home/canadian_training_kits.html.erb
<div id="diy-kits-page">
  <h1>DIY Kits<br/>Canadian Standards</h1>

  <h5>English Language<br/>
  Meets CSA/ANSI & Provincial Safety Standards</h5>

  <%= render 'shared/training_kit_header' %>

  <%= render 'shared/diy_kits_page' %>
</div>

app/views/home/index.html.erb
<div id="pendant">
  <hr id="blue-header-hr">
  <div class="pendant-image">
    <div class="pendant-text text-center">
      <span class="safety-training">Safety Training</span><br/>
      <span class="solutions">Solutions</span>
      <p class="tagline">
        Stop training the hard way.
        Try the Hard Hat Training way instead!
      </p>
    </div>
  </div>
  <div class="container-tri">
    <hr id="orange-header-hr" class="">
  </div>
</div>

<div class="container-tri">
<section class="section-white tri-above orange-tri-above">
  <h1>Who are we?</h1>
  <p class="h1-p">Your hub for OSHA-compliant, cost-effective safety training and certifications.</p>
  <%= link_to "More About Us", about_path, class: "orange-button" %>
</section>
</div>

<div class="container-tri">
  <section class="section-blue tri-above white-tri-above">
    <h2>Choose the way you train</h2>
    <h2>
      <span class="fa-stack">
        <i class="far fa-square fa-stack-2x"></i>
        <i class="fas fa-times fa-stack-1x"></i>
      </span>
      <span class="fa-stack">
        <i class="far fa-square fa-stack-2x"></i>
        <i class="fas fa-times fa-stack-1x"></i>
      </span>
      <span class="fa-stack">
        <i class="far fa-square fa-stack-2x"></i>
        <i class="fas fa-check fa-stack-1x"></i>
      </span>
    </h2>
    <div>
      <p class="text-justify hero-text">
        Want to train online? Check. Need to train a group? Would you prefer Onsite or Online? We've got both. Want to take a course in Spanish? You can do that. We even have a few in Tagalog! To top it off, all of our General Industry courses are OSHA-compliant, and our Canadian friends can get CSA/ANSI standards, too. With nearly two decades in the industry, it's almost like we know what we're doing.
      </p>
    </div>
  </section>
</div>

<div class="container-tri">
  <%= render 'shared/training_types' %>
</div>

<div class="container-tri">
  <section class="section-blue tri-above white-tri-above" id="how-training-works">
    <h2>How does our training work?</h2>
    <p>Watch this two minute video to find out</p>
    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/-yh8itnB41k?rel=0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </section>
</div>

<div class="container-tri">
  <section class="section-white tri-above blue-tri-above no-section-padding" id="why-train">
    <div class="two-col-left tri-above blue-tri-above">
      <%= image_tag "homepage-images/why-train-t-615x463.jpg", alt: "Why Train Image", id: "blog-img", class: "img-left-col" %>
    </div>
    <div class="two-col-right">
      <div class="two-col-right-text">
        <h2>Why Train?</h2>
        <p class="text-justify hero-text">
          The days of 15-minute operator certification via video or online course are over. It is simply not sufficient. If there is ever an accident, you will need to be able to prove comprehensive training. <em>Protect your company and your employees!</em>
        </p>
      </div>
    </div>
  </section>
</div>

<div class="container-tri">
  <section class="section-blue tri-above half-tri-above white-tri-above">
    <h2>Trusted by companies <br/>around the world</h2>
    <p class="hero-text">In virtually every industry</p>
  </section>
</div>

<div class="container-tri">
  <section class="section-white tri-above blue-tri-above" id="customer-logos-container">
    <%= image_tag "customers/nasa.png", alt: "nasa-logo", class: "customer-logo" %>
    <%= image_tag "customers/crane-institute-of-america.png", alt: "Crane Institute of America Logo", class: "customer-logo" %>
    <%= image_tag "customers/us-army-corps-of-engineers.png", alt: "US Army Corps of Engineers Logo", class: "customer-logo" %>
    <%= image_tag "customers/cat.png", alt: "CAT Logo", class: "customer-logo" %>
    <%= image_tag "customers/ge.png", alt: "GE Logo", class: "customer-logo" %>
  </section>
</div>

<div class="container-tri">
  <section class="section-blue tri-above white-tri-above" id="jump-to-courses">

    <h2>All The Training Topics You Need</h2>
    <p class="text-justify hero-text">
      With hundreds of courses, covering a multitude of topics, in multiple languages, compliant with OSHA and Canadian standards where relevant, you are sure to find the one you need!
    </p>
  </section>
</div>

<div class="container-tri">
  <section class="section-white tri-above blue-tri-above">
    <h2>Company Accounts Available!</h2>
    <%= image_tag "training-topic-icons/credits.png", alt: "Bulk Credits Icon", class: "topic-icon" %>

    <p class="text-justify hero-text">
      Save <em>time</em> and <em>money</em> on our Online Courses! Easily manage your employees' training, purchase discounted credits in bulk, assign courses <em>en masse</em>, download certificates, and more!
    </p>

    <p>
      <%= link_to 'Learn More', documentation_path(anchor: 'company-accounts'), class: 'btn btn-outline-primary' %>
    </p>

  </section>
</div>

<%# TODO THIS WILL BE FOR BLOG POSTS
<div class="container-tri">
  <section class="section-blue tri-above white-tri-above" id="blog-post-section">
    <h2>Most Recent Blog Post</h2>
  </section>
</div>

<div class="container-tri">
<section class="section-white tri-above blue-tri-above no-section-padding one-to-two-col">
  <div class="two-col-left">
%>
    <%#= image_tag "homepage-images/why-train-t-615x463.jpg", alt: "Why Train Image", id: "blog-img", class: "img-left-col" %>
<%# TODO THIS WILL BE FOR BLOG POSTS (Continued…)
  </div>
  <div class="two-col-right">
    <div class="two-col-right-text">
      <p class="text-justify">
        <span id="recent-blog-post-title" class="text-center">Trench Safety: 5 Common Hazards</span><br/>
        <span id="recent-blog-post-text">
          According to OSHA, trenching is a top job site hazard, which causes an average of 54 fatalities each year. One such fatality… <span> [ %><%#= link_to 'more', '#' %> <%#]</span>
        </span>
      </p>
    </div>
  </div>
</section>
</div>
%>
<%#= render 'shared/social_media_links' %>

app/views/home/search.html.erb
<h1 class="h1-margins">Search Results</h1>

<% if @exact_match.blank? %>
  <p>No exact matches.</p>
<% else %>

  <h3>Exact Match</h3>
  <div class="search-product-groups">
    <% @exact_match.each do |p| %>
      <%= link_to p do %>
        <div class="card" style="width: 18rem;">
          <%#= image_tag p.image.url, class: "card-img-top", alt: "Card image cap" %>
          <%= image_tag p.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title"><%= p.name %></h3>
            <% if p.alt_names.any? %>
              <p><em>
                a.k.a. <%= p.alt_names.pluck(:name).sort.join(', ') %>
              </em></p>
            <% end %>
            <p class="text-center"><small>Available in:</small></p>
            <ul>
              <li><%= flag_helper('usa', p) %></li>
              <li><%= flag_helper('canada', p) %></li>
              <li><%= flag_helper('spanish', p) %></li>
              <li><%= flag_helper('tagalog', p) %></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if @results.blank? %>
  <h3>Here are some other things you might like:</h3>
  <div class="search-product-groups">

    <% unless @button_group.nil? %>
      <%= link_to button_groups_path do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @button_group.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Buttons</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @card_groups.nil? %>
      <% @card_groups.each do |card_group| %>
        <%= link_to card_group do %>
          <div class="card" style="width: 18rem;">
            <%= image_tag card_group.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
            <div class="card-body">
              <h3 class="card-title search-card-title"><%= card_group.name %></h3>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <% unless @certificate.nil? %>
      <%= link_to @certificate do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @certificate.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Certificate of Completion</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @hat.nil? %>
      <%= link_to hats_path do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @hat.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Hats</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @keychain_group.nil? %>
      <%= link_to @keychain_group do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @keychain_group.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">CPR Keychains</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @lanyard_group.nil? %>
      <%= link_to @lanyard_group do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @lanyard_group.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Lanyards</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @machine_tag_group.nil? %>
      <%= link_to @machine_tag_group do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @machine_tag_group.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Pendant Warning Tags</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @poster_group.nil? %>
      <%= link_to poster_groups_path do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @poster_group.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Posters</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @shirt.nil? %>
      <%= link_to shirts_path do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @shirt.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Shirts</h3>
          </div>
        </div>
      <% end %>
    <% end %>

    <% unless @sticker.nil? %>
      <%= link_to stickers_path do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag @sticker.image_url(:small), class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title">Stickers</h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<% else %>

  <h3>Other Results</h3>
  <div class="search-product-groups">
    <% @results.each do |p| %>
      <%= link_to p do %>
        <div class="card" style="width: 18rem;">
          <%= image_tag p.image.url, class: "card-img-top", alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="card-title search-card-title"><%= p.name %></h3>
            <% if p.alt_names.any? %>
              <p><em>
                a.k.a. <%= p.alt_names.pluck(:name).join(', ') %>
              </em></p>
            <% end %>
            <p class="text-center"><small>Available in:</small></p>
            <ul>
              <li><%= flag_helper('usa', p) %></li>
              <li><%= flag_helper('canada', p) %></li>
              <li><%= flag_helper('spanish', p) %></li>
              <li><%= flag_helper('tagalog', p) %></li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/home/topics.html.erb
<div id="training-topics-page">
  <h1>All Training Topics</h1>

  <p>All of our training courses are available as <%= link_to "DIY Kits", diy_training_kits_path %>, <%= link_to "Online Courses", all_online_courses_path %>, <%= link_to "Train The Trainers", all_train_the_trainer_courses_path %>, <%= link_to "Group Trainings", all_group_trainings_path %>, or <%= link_to "Onsite", onsite_request_path %>!</p>

  <div id="topics-list">
    <p>Jump to a section:</p>
    <% @title.each do |t| %>
      <%= link_to t, "##{ kebabify(t) }" %>
    <% end %>
  </div>

  <div id="topics-container">
    <% @categories.each do |category| %>

      <section id="<%= kebabify(category.name) %>">
        <% logical_file_path = "training-topic-icons/#{ kebabify(category.name) }.png" %>

        <% topic_image = (::Sprockets::Railtie.build_environment(Rails.application).find_asset(logical_file_path)).present? ?
            logical_file_path :
            "training-topic-icons/hard-hat.png" %>

        <%= image_tag topic_image, alt: "fall-protection-icon", class: "topic-icon" %>
        <h4><%= category %></h4>

        <ul>
          <% @courses.tagged_with(category).each do |course| %>
            <%= link_to course, class: "topic-entry", "data-turbolinks": false, target: "_self" do %>
               <li><%= course.name %></li>
            <% end %>
          <% end %>
        </ul>
      </section>
    <% end %>
  </div>
</div>