config/routes.rb
    post 'companies/toggle_employee_status',        to: "application#toggle_employee_status"

    get  'companies/manage_employees',    to: "companies#manage_employees"
    # post 'companies/manage_employees',    to: "companies#manage_employees"

    get  'companies/homepage',            to: "companies#main"
    # post 'companies/homepage',            to: "companies#main"

    post 'companies/remove_employee', to: "application#remove_employee"

    # post '/download_validator',           to: "orders#download_validator"

    get '/assign_identifier',             to: "companies#assign_identifier"

    post '/assign_parent_company',        to: "companies#assign_parent_company"

    post '/remove_parent_company',        to: "companies#remove_parent_company"

    match '/assign_course', to: "companies#assign_course", via: [:get, :post]

    post 'companies/assign_multiple_courses',    to: "companies#assign_multiple_courses"

    get  'companies/orders',  to: "companies#company_orders"
    get  'companies/reports', to: "companies#company_reports"
    post '/get_talent_user_id', to: "talent#get_talent_user_id"

    # TODO Some of these should be moved to Superadmin!
    # get  'unpaid_orders',     to: "orders#unpaid_orders"
    # post 'invoiced',          to: "orders#invoiced"
    # post 'labeled',           to: "orders#labeled"
    # post 'order_paid',        to: "orders#order_paid"
    get  'mark_all_as_read',  to: "application#mark_all_as_read"
    post 'import_employees',  to: "companies#import_employees"

    resources :users # , only: [:show]
  # end

  # devise_scope :admin do
    get '/add_employee',            to: "users#add_employee"
    get '/manage_employees',        to: "users#manage_employees"
    post '/remove_employee',        to: "application#remove_employee"
    post '/toggle_employee_status', to: "application#toggle_employee_status"
    post '/make_assignable',        to: 'application#make_assignable'
  end

  # Superadmins only
  authenticated :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'

    resources :alt_names
    resources :backups
    resources :bulk_price_levels
    resources :button_groups
    resources :buttons
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychain_groups
    resources :keychains
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tag_groups
    resources :machine_tags
    resources :online_courses
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :product_groups
    resources :related_items
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users
    get  '/analytics',        to: 'reports#analytics'
    post '/assign_non_catalog_course', to: 'superadmin#assign_non_catalog_course'
    post 'invoiced',          to: "orders#invoiced"
    post 'labeled',           to: "orders#labeled"
    get  '/labels_required',  to: "users#labels_required"
    post 'order_paid',        to: "orders#order_paid"
    post 'related_items/new', to: "related_items#new"
    post '/reset_download_window',     to: 'superadmin#reset_download_window'
    get  'unpaid_orders',     to: "orders#unpaid_orders"
  end

  # These are required for things to show up in Administrate.
  namespace :admin do
    resources :alt_names
    resources :announcements
    resources :backups
    resources :bulk_price_levels
    resources :buttons
    resources :button_groups
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychains
    resources :keychain_groups
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tags
    resources :machine_tag_groups
    resources :non_catalog_course_accesses
    resources :notifications
    resources :orders do
      member do
        put :refund
      end
    end
    resources :online_courses
    resources :order_items #, only: [:create, :update]
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :products
    resources :product_groups
    resources :services
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users

    root to: "users#index"
  end

  # PUBLIC ROUTES
  get  'add_tag',               to: "product_groups#add_tag"
  get '/all_group_trainings',   to: 'home#all_group_trainings'
  get '/all_online_courses',    to: 'home#all_online_courses'
  post '/sales',                to: 'reports#sales'
  get '/all_train_the_trainer_courses',    to: 'home#all_train_the_trainer_courses'
  get  'remove_tag',            to: "product_groups#remove_tag"
  post  'add_tag_global',       to: "product_groups#add_tag_global"
  post  'remove_tag_global',    to: "product_groups#remove_tag_global"

  post '/add_to_course',        to: 'talent#online_course_validator'
  post '/add_backup',           to: 'order_items#add_backup'
  post '/add_shipping_address', to: 'checkouts#add_shipping_address'
  get '/about',                 to: 'home#about'
  get '/canadian_group_trainings',to: 'home#canadian_group_trainings'
  get '/canadian_online_courses',to: 'home#canadian_online_courses'
  get '/canadian_train_the_trainer_courses',to: 'home#canadian_train_the_trainer_courses'
  get '/canadian_training_kits',to: 'home#canadian_training_kits'
  get '/change_shipping',       to: 'orders#change_shipping'
  get '/contact_us',            to: 'home#contact'
  # This allows users to get their downloads from Orders!
  post '/download_validator',   to: "orders#download_validator"
  get '/diy_training_kits',     to: 'home#diy_training_kits'
  post '/edit_tag',             to: "tags#edit"
  get '/faq',                   to: 'home#faq'
  get '/course',                to: 'product_groups#course'
  post '/get_certificate',      to: 'talent#get_cert'
  get '/osha_group_trainings',  to: 'home#osha_group_trainings'
  get '/osha_online_courses',   to: 'home#osha_online_courses'
  get '/osha_train_the_trainer_courses',    to: 'home#osha_train_the_trainer_courses'
  get '/osha_training_kits',    to: 'home#osha_training_kits'
  get '/spanish_group_trainings',to: 'home#spanish_group_trainings'
  get '/spanish_online_courses',to: 'home#spanish_online_courses'
  get '/spanish_train_the_trainer_courses', to: 'home#spanish_train_the_trainer_courses'
  get '/spanish_training_kits', to: 'home#spanish_training_kits'
  get '/tagalog_group_trainings',to: 'home#tagalog_group_trainings'
  get '/tagalog_online_courses',to: 'home#tagalog_online_courses'
  get '/tagalog_train_the_trainer_courses', to: 'home#tagalog_train_the_trainer_courses'
  get '/tagalog_training_kits', to: 'home#tagalog_training_kits'
  post '/talent_login',         to: 'talent#log_into_talent'
  get '/training_topics',       to: 'home#topics'
  post '/update_tag',           to: "tags#update"
  post '/reset_password',       to: "application#reset_password"

  match '/onsite_request',      to: "home#onsite_training", via: [:get, :post]

  get '/remove_coupon_code',  to: "orders#remove_coupon_code"
  get '/search',              to: 'home#search'
  post '/send_contact_email', to: 'home#send_contact_email'
  get '/privacy',             to: 'home#privacy'
  get '/terms',               to: 'home#terms'
  get '/training_types',      to: 'home#training_types'
  post '/update_preferred_currency',      to: 'home#update_preferred_currency'
  get '/verify_code',         to: "orders#verify_code"
  get '/documentation',       to: 'documents#index'
  get 'employee_list',        to: 'reports#employee_list'
  get 'reports',              to: 'reports#index'

  resources :announcements, only: [:index]
  resources :button_groups, only: [:show, :index]
  resources :card_groups, only: [:show]
  resource :cart do
    resource :checkout
  end
  resources :certificates, only: [:show]
  resources :companies
  resources :credit_packs, only: [:index]
  resources :hats, only: [:show, :index]
  resources :keychain_groups, only: [:show]
  # TODO Should these be here? They are purchased through their ProductGroup
  # resources :kits, except: [:show]           # <-- ???
  resources :lanyard_groups, only: [:show]
  resources :machine_tag_groups, only: [:show]
  resources :notifications, only: [:index]
  # TODO Should these be here? They are purchased through ProductGroup
  # resources :online_courses, except: [:show] # <-- ???
  resources :order_items, only: [:create, :update]
  resources :orders
  resources :poster_groups, only: [:index, :show]
  resources :posters, only: [:show]
  resources :product_groups, only: [:show]
  # Uncomment if this gets used
  # resources :products, only: [:show]
  resources :shirts, only: [:show, :index]
  resources :stickers, only: [:show, :index]
  resources :users, only: [:show, :edit]

  # authenticate :user, lambda { |u| u.superadmin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  #   get  '/analytics', to: 'reports#analytics'
  #   post '/assign_non_catalog_course', to: 'superadmin#assign_non_catalog_course'
  #   post '/reset_download_window', to: 'superadmin#reset_download_window'
  # end

  # # Test Routes. Change as needed.
  # post '/edituser', to: 'users#talent_user_edit'
  # # post '/talent_user_delete', to: 'users#talent_user_delete'


  # match "/404", to: "errors#not_found", via: :all
  match "/404", to: "application#error_render_method", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # RoutingError
  # match "*path", to: "home#catch_404", via: :all

app/models/product_group.rb
class ProductGroup < ActiveRecord::Base # ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :alt_names
  has_many :kits
  has_many :online_courses
  has_many :related_items
  has_many :train_the_trainers

  acts_as_taggable_on :tags

  validates_presence_of :name, :image, :video, :overview, :training_standards, :facts, :fails

  # The old way
  include ProductGroupImageUploader::Attachment.new(:image) # adds an `image` virtual attribute
  # The new way
  # include ProductGroupImageUploader::Attachment(:image)

  def has_kits?
    self.kits.present?
  end

  def has_osha_kits?
    self.kits.map { |k| k.is_osha? }.any?
  end
end

app/controllers/admin/product_groups_controller.rb
module Admin
  class ProductGroupsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ProductGroup.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ProductGroup.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    def find_resource(param)
      ProductGroup.find_by!(slug: param)
    end
  end
end

app/helpers/product_groups_helper.rb
module ProductGroupsHelper

  # # NOTE This does not work as it should
  # def modal_section(product_type, title)
  #   if !product_type.empty?

  #     make_h2(title) +

  #     product_type.each do |pt|

  #       make_h4(pt) +

  #       make_h5(pt.language.capitalize) +

  #       make_h5(pt.standards.upcase) +

  #       make_h5(number_to_currency(pt.price / 100.0)) +

  #       make_button(pt.id, product_type.class)
  #     end
  #   end
  # end

  # private

  #   def make_h2(title)
  #     tag.h2 do
  #       title
  #     end
  #   end

  #   def make_h4(pt)
  #     tag.h4 do
  #       pt.oi_name
  #     end
  #   end

  #   def make_h5(attribute)
  #     tag.h5 do
  #       attribute
  #     end
  #   end

  #   def make_button(id, pt_class)
  #     button_to "Add to Cart", order_items_path(orderable_id: id, orderable_type: pt_class), method: :post, class: "btn btn-primary"
  #   end

end

app/views/product_groups/_form.html.erb
<div id="product-group-form" class="content-container">
  <%= form_with(model: product_group, local: true) do |form| %>
    <% if product_group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product_group.errors.count, "error") %> prohibited this product_group from being saved:</h2>

        <ul>
        <% product_group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-section">
      <h3>Header Image</h3>
      <p>
        <small>Must be 1198 x 530, < 75 KB.</small><br/>
        <small>Please verify that the dimensions are correct!</small><br/>
        <%= link_to "Compress Or Die", "https://compress-or-die.com", target: :_blank %> | <%= link_to "Unsplash", "https://unsplash.com", target: :_blank %>
      </p>
      <div class="form-group product-group-image-container">
        <% if product_group.image.present? %>
          <%= image_tag product_group.image_url, class: "product-group-image" %>
        <% end %>

        <%= form.hidden_field :image, value: product_group.cached_image_data %>

        <%#= form.label "Header Image (must be 1198 x 530, < 75 KB)" %>
        <%# if product_group.persisted? %>
        <%= form.file_field :image, class: 'form-control-file', id: "image-file-upload", required: (product_group.persisted? ? false : true) %>
      </div>
      <div class="form-group">
        <%= form.label :alt_text, "Alt Text" %>
        <%= form.text_field :alt_text, class: 'form-control' %>
      </div>
    </div>

    <div class="form-section">
      <h3>Name / Video</h3>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group col-md-6">
          <%= form.label :video, "Video (vooPlayer code, ie, MjA0NjIw)" %>
          <%= form.text_field :video, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Overview</h3>
      <div class="form-group">
        <%#= form.label :overview %>
        <%= form.hidden_field :overview, id: 'product_group_overview' %>
        <trix-editor input="product_group_overview"></trix-editor>
      </div>
    </div>

    <div class="form-section">
      <h3>Training Standards</h3>
      <div class="form-group">
        <%#= form.label :training_standards %>
        <%= form.hidden_field :training_standards %>
        <trix-editor input="product_group_training_standards"></trix-editor>
      </div>
    </div>

    <div class="form-section">
      <h3>Facts</h3>
      <div class="form-group">
        <%#= form.label :facts %>
        <%= form.hidden_field :facts %>
        <trix-editor input="product_group_facts"></trix-editor>
      </div>
    </div>

    <div class="form-section">
      <h3>Fails / In The News</h3>
      <div class="form-group">
        <%#= form.label :fails %>
        <%= form.hidden_field :fails %>
        <trix-editor input="product_group_fails"></trix-editor>
      </div>
    </div>

    <div class="form-section">
      <h3>SEO</h3>
      <div class="form-group">
        <%= form.label :keywords %>
        <%= form.text_area :keywords, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= javascript_include_tag "char_counter" %>
        <%#= form.label :meta_description, "Meta Description" %>
        <label for="meta_description">Meta Description (<span id="metaDescription">0</span> / 160)</label>
        <%= form.text_area :meta_description, class: 'form-control', onkeyup: "countChars(this);" %>
      </div>
    </div>

    <div class="form-section">
      <h3 class="h3-margins">Availability</h3>
      <p class="h3-margins"><em><span>
        Check the box to make this item active/available.
      </span></em></p>
      <div class="form-group">
        <%= form.check_box :active %>
        <%= form.label "Active?", style: "display: inline;" %>
      </div>
    </div>

    <div class="form-group">
      <% if product_group.persisted? && Rails.env.development? %>
        <div class="float-right">
          <%= link_to 'Destroy', product_group, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>

      <%= form.submit class: 'btn btn-primary btn-spinner' %>

      <% if product_group.persisted? %>
        <%= link_to "Cancel", product_group, class: "btn btn-link" %>
      <% else %>
        <%= link_to "Cancel", product_groups_path, class: "btn btn-link" %>
      <% end %>
    </div>

    <% if !product_group.new_record? %>
      <hr>

      <div class="container">
        <div class="row" id="product-group-categories">
          <h2>Categories</h2>
          <h5>Which Categories Does This Product Group Belong To?</h5>
          <div class="col-6-md offset-md-3 align-self-center product-group-categories">
            <% @categories.each do |category| %>

              <% if product_group.tag_list.include?(category.name) %>
                <%= link_to category, remove_tag_path(tag: category.name, id: product_group.id), class: 'btn btn-success btn-product-group btn-sm' %>
              <% else %>
                <%= link_to category, add_tag_path(tag: category.name, id: product_group.id), class: 'btn btn-light btn-product-group btn-sm' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

  <% end %>
</div>

app/views/product_groups/edit.html.erb
<h1 class="h1-margins">Edit Product Group</h1>

<%= render 'form', product_group: @product_group %>

app/views/product_groups/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1 class="h1-margins">Product Groups</h1>
  </div>

  <div class="col-sm-6 text-right h1-margins">
  <%= link_to new_product_group_path, class: 'btn btn-primary' do %>
    Add New Product group
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

        <th>Name</th>
        <th>Active?</th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @product_groups.each do |product_group| %>
        <%= content_tag :tr, id: dom_id(product_group), class: dom_class(product_group) do %>

          <td>
            <%= product_group.name %>
            <%#= link_to 'Destroy', product_group, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
          </td>
          <td>
            <% if product_group.active == true %>
              <%= icon("fas", "check", class: "green") %>
            <% else %>
              <span style="font-weight: bold; color: red;">X</span>
            <% end %>
          </td>
          <td><%= link_to 'Edit', edit_product_group_path(product_group), class: 'btn btn-primary' %> <%= link_to "View", product_group, class: 'btn btn-success' %></td>

        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/product_groups/new.html.erb
<h1 class="h1-margins">New Product Group</h1>

<%= render 'form', product_group: @product_group %>

app/views/product_groups/show.html.erb
<%
  meta_title "#{ @product_group.name } | Hard Hat Training"
  meta_keywords "#{ @product_group.keywords }"
  meta_description "#{ @product_group.meta_description }"
%>

<% content_for :page_scripts do %>
  <script>
      var anchors = document.getElementById('fails').getElementsByTagName('a');
      for (var i=0; i<anchors.length; i++){
        anchors[i].setAttribute('target', '_blank');
        anchors[i].setAttribute('rel', 'noopener');
      }
  </script>
<% end %>

<section id="pendant">
  <hr id="blue-header-hr">
  <% @image = (@product_group.image_url(:large) || image_path('development/no-product-group-image.jpg')) %>
  <section style="background: url(<%= @image %>); display: grid; background-size: cover; background-position: center center; width: 100%; height: 100%;" title="<%= @alt_text %>">
    <section class="pendant-text">
        <span class="product-title-container">
          <p id="product-title" class="product-title">
              <%= @product_group.name %>
          </p>
          <p class="safety-training">
            Safety Training
          </p>
        </span>

      <%#= render 'shared/purchase' %>

    </section>
  </section>
  <div class="container-tri">
    <hr id="orange-header-hr">
  </div>
</section>

<div class="container-tri">
  <section class="section-white tri-above orange-tri-above">

    <% if user_signed_in? && current_user.superadmin? %>
      <%= link_to "All Product Groups", product_groups_path, class: "h1-margins btn btn-primary" %>
    <% end %>

    <% if @product_group.alt_names.any? %>
      <h3 class="h3-margins">
        <%= @product_group.name %> is also known as:<br/>
        <%= @product_group.alt_names.pluck(:name).sort.join(", ") %>
      </h3>
    <% end %>

    <% if @product_group.active == true %>
      <p class="text-center"><small>JUMP TO:</small></p>
      <div id="product-group-onpage-menu">
        <%= link_to "DIY Kits", "##{ kebabify(@product_group.name) }-kit-all", class: "btn btn-link #{ @kits.any? ? '' : 'disabled' }" %>
        <%= link_to "Group Training", "##{ kebabify(@product_group.name) }-grouptraining-all", class: "btn btn-link #{ @group_trainings.any? ? '' : 'disabled' }" %>
        <%= link_to "Online Courses", "##{ kebabify(@product_group.name) }-onlinecourse-all", class: "btn btn-link #{ @online_courses.any? ? '' : 'disabled' }" %>
        <%= link_to "Onsite Training", "##{ kebabify(@product_group.name) }-onsite", class: "btn btn-link" %>
        <%= link_to "Train the Trainer", "##{ kebabify(@product_group.name) }-trainthetrainer-all", class: "btn btn-link #{ @train_the_trainers.any? ? '' : 'disabled' }" %>
        <%= link_to "Overview", "#overview", class: "btn btn-link" %>
        <%= link_to "Requirements", "#requirements", class: "btn btn-link" %>
        <%= link_to "Standards", "#standards", class: "btn btn-link" %>
        <%= link_to "Facts", "#facts", class: "btn btn-link" %>
        <%= link_to "Fails", "#fails", class: "btn btn-link" %>
      </div>

      <%= render 'shared/black_purchase_button', items: @online_courses, item_type: 'OnlineCourse', item_header: 'Online Courses', icon_name: 'desktop' %>

      <%= render 'shared/black_purchase_button', items: @kits, item_type: 'Kit', item_header: 'DIY Kits', icon_name: 'briefcase' %>

      <%= render 'shared/black_purchase_button', items: @train_the_trainers, item_type: 'TrainTheTrainer', item_header: 'Train the Trainer', icon_name: 'chalkboard-teacher' %>

      <%= render 'shared/black_purchase_button', items: @products, item_type: 'Product', item_header: 'Physical Products', icon_name: 'tshirt' %>

      <%= render 'shared/black_purchase_button', items: @group_trainings, item_type: 'GroupTraining', item_header: 'Group Training', icon_name: 'users' %>

      <div class="modal-section">
        <h5 id="<%= kebabify(@product_group.name) %>-onsite">
          <span>
            <%= icon("fas", "angle-double-left") %>
          </span>
          <%= @product_group.name %>
          <span>
            <%= icon("fas", "angle-double-right") %>
          </span>
        </h5>
        <h2>
          <%= icon("fas", 'map-marker-alt' ) %> Onsite Training
        </h2>

        <div class="whats-this">
          <%= link_to '#', 'data-toggle': "modal", 'data-target': "#onsite-training" do %>
            <%= icon("fas", "info-circle") %> What's this?
          <% end %>
        </div>

        <p class="modal-note">
          Want an expert to bring the training to you? Operator Training, Train the Trainer, or both, we've got you covered! Give us a few details and we'll get back to you with a quote.
        </p>

        <%= button_to "Request Quote", onsite_request_path(pg_name: @product_group.name), method: :post, class: "btn btn-primary" %>
      </div>
    <% else %>
      <h5>This training is currently unavailable.</h5>
    <% end %>
  </section>
</div>

<div class="container-tri">
  <section class="section-blue tri-above white-tri-above">
    <div id="triangle" class="white-triangle"></div>

    <% if !@product_group.video.blank? %>
      <iframe class="vooplayer" allowtransparency="true" allowfullscreen="true" src="https://safetyprovisions.cdn.vooplayer.com/publish/<%= @product_group.video %>?fallback=true" frameborder="0" scrolling="no"></iframe>
    <% end %>

  </section>
</div>

<div class="container-tri">
  <section class="section-white tri-above blue-tri-above product-group-text" id="overview">
    <h1 class="product-title"><%= @product_group.name.upcase %> OVERVIEW</h1>
    <% if @alt_names.any? %>
      <h5>Also Known As:</h5>
      <div id="alt-names">
        <% @alt_names.pluck(:name).each do |name| %>
          <span><%= name %></span>
        <% end %>
      </div>
    <% end %>
    <%= sanitize @product_group.overview %>
  </section>
</div>

<div class="container-tri">
  <section class="section-blue tri-above white-tri-above product-group-text" id="requirements">
    <div id="triangle" class="white-triangle"></div>
    <h2 id="why-you-need-training-header">Why you need training</h2>
    <div>
      In line with OSHA requirements, anyone who operates heavy equipment must receive training prior to operating the machine on their own. OSHA requirements for refresher training related to forklifts or other processes are very specific. Most other equipment doesn’t have such specific requirements, but it’s wise to follow the same guidelines.
    <br/><br/>
      When it comes to refresher training, OSHA’s standard in some instances (like forklifts) are very specific: operators must be re-evaluated every three years to see if they are still competent to operate the equipment. Best practices say to apply this same rule to all types of equipment. A so-called “free pass” cannot be awarded based on experience, age, or time on the job. The extent of the evaluation is to be determined by the employer, but should include a written and practical examination that prove continued competency.
    </div>
  </section>
</div>

<div class="container-tri">
  <section class="section-white tri-above blue-tri-above product-group-text standards-section" id="standards">
    <h2>This Training Encompasses</h2>
    <%= sanitize @product_group.training_standards %>
  </section>
</div>

<div class="container-tri">
  <section class="section-blue tri-above tri-below white-tri-above blue-tri-below product-group-section-list product-group-text" id="facts">
    <h2>The Cold Hard Facts</h2>
    <span>
      <%= sanitize @product_group.facts %>
    </span>
  </section>
</div>

<div class="container-tri" id="fails">
  <section class="section-white tri-above blue-tri-above product-group-section-list product-group-text">
    <h2><span class="product-title"><%= @product_group.name.upcase %></span> Safety Fails</h2>
    <%= sanitize @product_group.fails %>
  </section>
</div>

<%= render 'shared/whats_this' %>