config/routes.rb
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions',
    registrations:  'users/registrations'
  }

  # devise_scope :user do
  #   authenticated :user do
  #     root :to => 'pages#other', as: :authenticated_root
  #   end
  #   unauthenticated :user do
  #     root :to => 'sessions#new', as: :unauthenticated_root
  #   end
  # end

  devise_for :companies, controllers: {
    sessions:       'companies/sessions',
    registrations:  'companies/registrations'
  }


  # Admins only *** NOT Superadmins! ***
  authenticated :user, lambda { |u| u.admin? } do
  # devise_scope :companies do
    root to: "companies#main"

    post '/users/new', to: 'users#existence_check'

    get  'companies/branch_view',         to: "companies#branch_view"
    # post 'companies/branch_view',         to: "companies#branch_view"

    get  'companies/add_employee',        to: "companies#add_employee"
    # post 'companies/add_employee',        to: "companies#add_employee"

    post 'companies/toggle_admin',        to: "companies#toggle_admin"

    post 'companies/toggle_employee_status',        to: "application#toggle_employee_status"

    get  'companies/manage_employees',    to: "companies#manage_employees"
    # post 'companies/manage_employees',    to: "companies#manage_employees"

    get  'companies/homepage',            to: "companies#main"
    # post 'companies/homepage',            to: "companies#main"

    post 'companies/remove_employee', to: "application#remove_employee"

    # post '/download_validator',           to: "orders#download_validator"

    get '/assign_identifier',             to: "companies#assign_identifier"

    post '/assign_parent_company',        to: "companies#assign_parent_company"

    post '/remove_parent_company',        to: "companies#remove_parent_company"

    match '/assign_course', to: "companies#assign_course", via: [:get, :post]

    post 'companies/assign_multiple_courses',    to: "companies#assign_multiple_courses"

    get  'companies/orders',  to: "companies#company_orders"
    get  'companies/reports', to: "companies#company_reports"
    post '/get_talent_user_id', to: "talent#get_talent_user_id"

    # TODO Some of these should be moved to Superadmin!
    # get  'unpaid_orders',     to: "orders#unpaid_orders"
    # post 'invoiced',          to: "orders#invoiced"
    # post 'labeled',           to: "orders#labeled"
    # post 'order_paid',        to: "orders#order_paid"
    get  'mark_all_as_read',  to: "application#mark_all_as_read"
    post 'import_employees',  to: "companies#import_employees"

    resources :users # , only: [:show]
  # end

  # devise_scope :admin do
    get '/add_employee',            to: "users#add_employee"
    get '/manage_employees',        to: "users#manage_employees"
    post '/remove_employee',        to: "application#remove_employee"
    post '/toggle_employee_status', to: "application#toggle_employee_status"
    post '/make_assignable',        to: 'application#make_assignable'
  end

  # Superadmins only
  authenticated :user, lambda { |u| u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'

    resources :alt_names
    resources :backups
    resources :bulk_price_levels
    resources :button_groups
    resources :buttons
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychain_groups
    resources :keychains
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tag_groups
    resources :machine_tags
    resources :online_courses
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :product_groups
    resources :related_items
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users
    get  '/analytics',        to: 'reports#analytics'
    post '/assign_non_catalog_course', to: 'superadmin#assign_non_catalog_course'
    post 'invoiced',          to: "orders#invoiced"
    post 'labeled',           to: "orders#labeled"
    get  '/labels_required',  to: "users#labels_required"
    post 'order_paid',        to: "orders#order_paid"
    post 'related_items/new', to: "related_items#new"
    post '/reset_download_window',     to: 'superadmin#reset_download_window'
    get  'unpaid_orders',     to: "orders#unpaid_orders"
  end

  # These are required for things to show up in Administrate.
  namespace :admin do
    resources :alt_names
    resources :announcements
    resources :backups
    resources :bulk_price_levels
    resources :buttons
    resources :button_groups
    resources :card_groups
    resources :cards
    resources :certificates
    resources :companies
    resources :coupon_codes
    resources :credit_packs
    resources :digital_posters
    resources :group_trainings
    resources :hats
    resources :keychains
    resources :keychain_groups
    resources :kits
    resources :lanyard_groups
    resources :lanyards
    resources :machine_tags
    resources :machine_tag_groups
    resources :non_catalog_course_accesses
    resources :notifications
    resources :orders do
      member do
        put :refund
      end
    end
    resources :online_courses
    resources :order_items #, only: [:create, :update]
    resources :payment_terms
    resources :poster_groups
    resources :posters
    resources :products
    resources :product_groups
    resources :services
    resources :shirts
    resources :stickers
    resources :train_the_trainers
    resources :users

    root to: "users#index"
  end

  # PUBLIC ROUTES
  get  'add_tag',               to: "product_groups#add_tag"
  get '/all_group_trainings',   to: 'home#all_group_trainings'
  get '/all_online_courses',    to: 'home#all_online_courses'
  post '/sales',                to: 'reports#sales'
  get '/all_train_the_trainer_courses',    to: 'home#all_train_the_trainer_courses'
  get  'remove_tag',            to: "product_groups#remove_tag"
  post  'add_tag_global',       to: "product_groups#add_tag_global"
  post  'remove_tag_global',    to: "product_groups#remove_tag_global"

  post '/add_to_course',        to: 'talent#online_course_validator'
  post '/add_backup',           to: 'order_items#add_backup'
  post '/add_shipping_address', to: 'checkouts#add_shipping_address'
  get '/about',                 to: 'home#about'
  get '/canadian_group_trainings',to: 'home#canadian_group_trainings'
  get '/canadian_online_courses',to: 'home#canadian_online_courses'
  get '/canadian_train_the_trainer_courses',to: 'home#canadian_train_the_trainer_courses'
  get '/canadian_training_kits',to: 'home#canadian_training_kits'
  get '/change_shipping',       to: 'orders#change_shipping'
  get '/contact_us',            to: 'home#contact'
  # This allows users to get their downloads from Orders!
  post '/download_validator',   to: "orders#download_validator"
  get '/diy_training_kits',     to: 'home#diy_training_kits'
  post '/edit_tag',             to: "tags#edit"
  get '/faq',                   to: 'home#faq'
  get '/course',                to: 'product_groups#course'
  post '/get_certificate',      to: 'talent#get_cert'
  get '/osha_group_trainings',  to: 'home#osha_group_trainings'
  get '/osha_online_courses',   to: 'home#osha_online_courses'
  get '/osha_train_the_trainer_courses',    to: 'home#osha_train_the_trainer_courses'
  get '/osha_training_kits',    to: 'home#osha_training_kits'
  get '/spanish_group_trainings',to: 'home#spanish_group_trainings'
  get '/spanish_online_courses',to: 'home#spanish_online_courses'
  get '/spanish_train_the_trainer_courses', to: 'home#spanish_train_the_trainer_courses'
  get '/spanish_training_kits', to: 'home#spanish_training_kits'
  get '/tagalog_group_trainings',to: 'home#tagalog_group_trainings'
  get '/tagalog_online_courses',to: 'home#tagalog_online_courses'
  get '/tagalog_train_the_trainer_courses', to: 'home#tagalog_train_the_trainer_courses'
  get '/tagalog_training_kits', to: 'home#tagalog_training_kits'
  post '/talent_login',         to: 'talent#log_into_talent'
  get '/training_topics',       to: 'home#topics'
  post '/update_tag',           to: "tags#update"
  post '/reset_password',       to: "application#reset_password"

  match '/onsite_request',      to: "home#onsite_training", via: [:get, :post]

  get '/remove_coupon_code',  to: "orders#remove_coupon_code"
  get '/search',              to: 'home#search'
  post '/send_contact_email', to: 'home#send_contact_email'
  get '/privacy',             to: 'home#privacy'
  get '/terms',               to: 'home#terms'
  get '/training_types',      to: 'home#training_types'
  post '/update_preferred_currency',      to: 'home#update_preferred_currency'
  get '/verify_code',         to: "orders#verify_code"
  get '/documentation',       to: 'documents#index'
  get 'employee_list',        to: 'reports#employee_list'
  get 'reports',              to: 'reports#index'

  resources :announcements, only: [:index]
  resources :button_groups, only: [:show, :index]
  resources :card_groups, only: [:show]
  resource :cart do
    resource :checkout
  end
  resources :certificates, only: [:show]
  resources :companies
  resources :credit_packs, only: [:index]
  resources :hats, only: [:show, :index]
  resources :keychain_groups, only: [:show]
  # TODO Should these be here? They are purchased through their ProductGroup
  # resources :kits, except: [:show]           # <-- ???
  resources :lanyard_groups, only: [:show]
  resources :machine_tag_groups, only: [:show]
  resources :notifications, only: [:index]
  # TODO Should these be here? They are purchased through ProductGroup
  # resources :online_courses, except: [:show] # <-- ???
  resources :order_items, only: [:create, :update]
  resources :orders

app/models/certificate.rb
class Certificate < ApplicationRecord
  include CertificateImageUploader::Attachment.new(:image) # adds an `image` virtual attribute

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :order_items, as: :orderable

  validates_presence_of :name, :description, :image, :keywords, :meta_description, :price, :cad_price, :shipping_price, :priority_shipping, :intl_shipping

  def product_group
    ""
  end

  def language
    ""
  end

  def standards
    ""
  end

  def current_price
    price
  end

  def cad_current_price
    cad_price
  end

  def oi_name
    name
  end

  def weight
    10
  end
end

app/controllers/admin/certificates_controller.rb
module Admin
  class CertificatesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Certificate.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    def find_resource(param)
      Certificate.find_by!(slug: param)
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  def index
    @certificates = Certificate.all
  end

  def show
  end

  def new
    @certificate = Certificate.new
  end

  def edit
  end

  def create
    @certificate = Certificate.new(certificate_params)
    @certificate.image_derivatives! # generate Shrine derivatives

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully created.' }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        @certificate.image_derivatives! # generate Shrine derivatives
        @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: 'Certificate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_certificate
      @certificate = Certificate.friendly.find(params[:id])
    end

    def certificate_params
      params.require(:certificate).permit(:name, :description, :image, :slug, :keywords, :meta_description, :price, :cad_price, :shipping_price, :priority_shipping, :intl_shipping, :active)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<div id="certificate-form" class="content-container">
  <%= form_with(model: certificate, local: true) do |form| %>
    <% if certificate.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h3>

        <ul>
        <% certificate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-section">
      <h3>Name</h3>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :title, class: 'form-control', placeholder: 'Name' %>
      </div>
    </div>

    <div class="form-section">
      <h3>Description</h3>
      <div class="form-group">
        <%= form.hidden_field :description, id: 'certificate_description' %>
        <trix-editor input="certificate_description", class="text-left"></trix-editor>
      </div>
    </div>

    <div class="form-section">
      <h3 class="h3-margins">Image</h3>
      <p>
        <small>
          Must be 400 x 400, < 75 KB
        </small>
      </p>
      <div class="form-group product-group-image-container">
        <% if certificate.image.present? %>
          <%= image_tag certificate.image_url, class: "product-group-image" %>
        <% end %>

        <%= form.hidden_field :image, value: certificate.cached_image_data %>

        <%= form.file_field :image, class: 'form-control-file' %>
      </div>
    </div>

    <div class="form-section">
      <h3 class="h3-margins">Metatags</h3>
      <div class="form-group">
        <%= form.label :keywords %>
        <%= form.text_area :keywords, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :meta_description %>
        <%= form.text_area :meta_description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-section">
      <h3 class="h3-margins">Pricing</h3>
      <p class="h3-margins"><small>In cents (ie, $35 => 3500)</small></p>
      <div class="row">
        <div class="form-group col-sm-6">
          <%= form.label :price, "USD" %>
          <%= form.number_field :price, class: 'form-control' %>
        </div>

        <div class="form-group col-sm-6">
          <%= form.label :cad_price, "CAD" %>
          <%= form.number_field :cad_price, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3 class="h3-margins">Shipping</h3>
      <p class="h3-margins"><small>In cents (ie, $10 => 1000)</small></p>
      <div class="row">
        <div class="form-group col-sm-4">
          <%= form.label :shipping_price, "Basic" %>
          <%= form.number_field :shipping_price, class: 'form-control' %>
        </div>

        <div class="form-group col-sm-4">
          <%= form.label :priority_shipping, "Priority" %>
          <%= form.number_field :priority_shipping, class: 'form-control' %>
        </div>

        <div class="form-group col-sm-4">
          <%= form.label :intl_shipping, "International" %>
          <%= form.number_field :intl_shipping, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3 class="h3-margins">Availability</h3>
      <p class="h3-margins"><em><span>
        Check the box to make this item active/available.
      </span></em></p>
      <div class="form-group">
        <%= form.check_box :active %>
        <%= form.label "Active?", style: "display: inline;" %>
      </div>
    </div>

    <div class="form-group">
      <% if certificate.persisted? && Rails.env.development? %>
        <div class="float-right">
          <%= link_to 'Destroy', certificate, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>

      <%= form.submit class: 'btn btn-primary' %>

      <% if certificate.persisted? %>
        <%= link_to "Cancel", certificate, class: "btn btn-link" %>
      <% else %>
        <%= link_to "Cancel", certificates_path, class: "btn btn-link" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/certificates/edit.html.erb
<h1 class="h1-margins">Edit Certificate</h1>

<%= render 'form', certificate: @certificate %>

app/views/certificates/index.html.erb
<h1 class="h1-margins text-center">Certificates</h1>

<%= link_to new_certificate_path, class: 'btn btn-primary h3-margins' do %>
  Add New Certificate
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

        <th>Name</th>
        <th>Price</th>
        <th>Shipping (Domestic/Priority/International)</th>
        <th>Active?</th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @certificates.each do |certificate| %>
        <%= content_tag :tr, id: dom_id(certificate), class: dom_class(certificate) do %>

          <td><%= certificate.name %></td>
            <td><%= number_to_currency(certificate.price.to_f / 100) %> (USD) / <%= number_to_currency(certificate.cad_price.to_f / 100) %> (CAD)</td>
            <td>
              <%= number_to_currency(certificate.shipping_price.to_f / 100) %> /
              <%= number_to_currency(certificate.priority_shipping.to_f / 100) %> /
              <%= number_to_currency(certificate.intl_shipping.to_f / 100) %>
            </td>
            <td>
              <% if certificate.active == true %>
                <%= icon("fas", "check", class: "green") %>
              <% else %>
                <%= icon("fas", "times", class: "red") %>
              <% end %>
            </td>
            <td>
              <%= link_to 'View', certificate, class: 'btn btn-success' %>
              <%= link_to 'Edit', edit_certificate_path(certificate), class: 'btn btn-primary' %>
            </td>

        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/certificates/new.html.erb
<h1 class="h1-margins">New Certificate</h1>

<%= render 'form', certificate: @certificate %>

app/views/certificates/show.html.erb
<%
  meta_title "#{ @certificate.name } | Hard Hat Training"
  meta_keywords "#{ @certificate.keywords }"
  meta_description "#{ @certificate.meta_description }"
%>
<div id="certificates-show">
  <div class="page-header">
    <% if user_signed_in? && current_user.superadmin? %>
      <%= link_to certificates_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        All Certificates
      <% end %>
      <%= link_to edit_certificate_path(@certificate), class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-pencil"></span>
        Edit
      <% end %>
    <% end %>
    <h1 class="h1-margins"><%= @certificate.name %></h1>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm" id="certificate-image-container">
        <%= image_tag @certificate.image_url, class: "width-100 mb-20" %>
      </div>
      <div class="col-sm text-left" id="certificate-text-container">
        <p><%= sanitize @certificate.description %></p>
        <%= content_tag :p, "#{ number_to_currency((session[:preferred_currency] == 'usd' ? @certificate.price : @certificate.cad_price).to_f / 100) } #{ session[:preferred_currency].upcase }", class: "price-lg-gray" %>
      </div>
    </div>

    <% if @certificate.active == true %>
      <div class="row" id="certificate-verification-form">
        <% if user_signed_in? %>
          <div class="form-group col-md-4 offset-md-4">
            <%= form_with(url: order_items_path, local: true) do |form| %>
              <%= form.hidden_field :orderable_id, value: @certificate.id %>
              <%= form.hidden_field :orderable_type, value: "Certificate" %>

              <%= form.label :trainee, "Trainee Name", class: "text-left" %>
              <%= form.text_field :trainee, placeholder: "Trainee Name", class: "form-control" %>

              <%= form.label :course_name, "Course Taken", class: "text-left" %>
              <%= form.select(:course_name, options_for_select(ProductGroup.all.order(name: :asc).pluck(:name)), { include_blank: true }, { class: "form-control" }) %>

              <%= form.label :training_date, "Training Date", class: "text-left" %>
              <%= date_field("certificate", "training_date", value: Date.today, class: "form-control") %>

              <%= form.submit "Add to Cart", class: 'btn btn-primary' %>
            <% end %>
          </div>
        <% else %>
          <div class="logged-out" style="display: block; margin: 0 auto;">
            <%= link_to "Create An Account", new_user_registration_path(login_redirect: request.original_url) %> or <%= link_to "Log In", new_user_session_path(login_redirect: request.original_url) %> to purchase!
          </div>
        <% end %>
      </div>
    <% else %>
      <h5 class="text-center h1-margins">This item is currently unavailable.</h5>
    <% end %>
  </div>
</div>